[package]
name = "aln-syntax"
version = "0.1.0"
authors = ["Bio-Aug Contributors <security@bio-aug.example>"]
edition = "2021"

[lib]
name = "aln_syntax"
path = "src/lib.rs"

[dependencies]
pest = "2.6"
pest_derive = "2.6"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
