[package]
name = "aln-check"
version = "0.1.0"
edition = "2021"

[dependencies]
aln-syntax = { path = "../aln-syntax" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.1"

[lib]
name = "aln_check"
path = "src/lib.rs"
